export const THEMES: Record<string, Record<string, string>> = {
  light: {
    "--color-bg-primary": "#ffffff",
    "--color-bg-secondary": "#f7f8fa",
    "--color-bg-sidebar": "#f7f8fa",
    "--color-bg-hover": "#f0f1f3",
    "--color-bg-hover-blue": "#eef1f5",
    "--color-bg-active": "#e8e9eb",
    "--color-bg-elevated": "#ffffff",
    "--color-bg-frosted": "rgba(255, 255, 255, 0.95)",
    "--color-text-heading": "#222222",
    "--color-text-primary": "#333333",
    "--color-text-secondary": "#555555",
    "--color-text-tertiary": "#888888",
    "--color-text-light": "#999999",
    "--color-text-muted": "#aaaaaa",
    "--color-border-light": "#eeeeee",
    "--color-border-medium": "#e0e0e0",
    "--color-border-input": "#dddddd",
  },
  newspaper: {
    "--color-bg-primary": "#f5f0e8",
    "--color-bg-secondary": "#ede7dd",
    "--color-bg-sidebar": "#ede7dd",
    "--color-bg-hover": "#e5ded3",
    "--color-bg-hover-blue": "#e2dbd0",
    "--color-bg-active": "#d9d1c5",
    "--color-bg-elevated": "#f5f0e8",
    "--color-bg-frosted": "rgba(245, 240, 232, 0.95)",
    "--color-text-heading": "#1a1611",
    "--color-text-primary": "#2d2821",
    "--color-text-secondary": "#5c5347",
    "--color-text-tertiary": "#8a7e70",
    "--color-text-light": "#a69888",
    "--color-text-muted": "#bfb1a0",
    "--color-border-light": "#ddd5c9",
    "--color-border-medium": "#ccc3b5",
    "--color-border-input": "#c2b8a9",
  },
  charcoal: {
    "--color-bg-primary": "#363839",
    "--color-bg-secondary": "#3c3e40",
    "--color-bg-sidebar": "#3c3e40",
    "--color-bg-hover": "#474a4c",
    "--color-bg-hover-blue": "#454850",
    "--color-bg-active": "#515456",
    "--color-bg-elevated": "#3e4042",
    "--color-bg-frosted": "rgba(54, 56, 57, 0.95)",
    "--color-text-heading": "#dcdcdc",
    "--color-text-primary": "#bcbcbc",
    "--color-text-secondary": "#8c8c8c",
    "--color-text-tertiary": "#6c6c6c",
    "--color-text-light": "#585858",
    "--color-text-muted": "#484848",
    "--color-border-light": "#3c3e41",
    "--color-border-medium": "#4a4c4f",
    "--color-border-input": "#555759",
    "--color-table-border": "#6a6d70",
  },
  dark: {
    "--color-bg-primary": "#1e1e1e",
    "--color-bg-secondary": "#252526",
    "--color-bg-sidebar": "#252526",
    "--color-bg-hover": "#2a2d2e",
    "--color-bg-hover-blue": "#2a2d3e",
    "--color-bg-active": "#333333",
    "--color-bg-elevated": "#2d2d2d",
    "--color-bg-frosted": "rgba(30, 30, 30, 0.95)",
    "--color-text-heading": "#e0e0e0",
    "--color-text-primary": "#cccccc",
    "--color-text-secondary": "#999999",
    "--color-text-tertiary": "#666666",
    "--color-text-light": "#555555",
    "--color-text-muted": "#444444",
    "--color-border-light": "#333333",
    "--color-border-medium": "#444444",
    "--color-border-input": "#555555",
    "--color-table-border": "#606060",
  },
};
